export function Terms() {
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '2rem', color: 'var(--text)', lineHeight: '1.8' }}>
      <h1 style={{ marginBottom: '0.5rem' }}>Terms of Service</h1>
      <p style={{ color: 'var(--text-muted)', marginBottom: '2rem' }}>Last updated: 2 August 2026</p>

      <p>These Terms of Service ("Terms") govern your access to and use of LumenSocial and all related services operated under sae963.com (collectively, "the Services"), owned and operated by S.A.E&trade; / Sylvana Ellis ("we", "us", "our"). By accessing or using the Services you agree to be bound by these Terms.</p>

      <h2 style={{ marginTop: '2rem' }}>1. Acceptable Use</h2>
      <p>You may use the Services only for lawful purposes and in accordance with these Terms. You agree not to:</p>
      <ul>
        <li>Use the Services to publish content that is unlawful, harmful, defamatory, obscene, or otherwise objectionable</li>
        <li>Violate the terms of service of any connected social media platform</li>
        <li>Attempt to gain unauthorised access to any part of the Services or connected accounts</li>
        <li>Use the Services to distribute spam, malware, or deceptive content</li>
        <li>Reverse engineer, decompile, or attempt to extract the source code of the Services</li>
        <li>Use automated means to access the Services beyond the functionality provided</li>
      </ul>

      <h2 style={{ marginTop: '2rem' }}>2. User Responsibilities</h2>
      <p>You are solely responsible for:</p>
      <ul>
        <li>All content you create, schedule, approve, or publish through the Services</li>
        <li>Ensuring that content you publish complies with all applicable laws and platform policies</li>
        <li>Maintaining the confidentiality of your account credentials</li>
        <li>Any activity that occurs under your account</li>
        <li>Obtaining all necessary rights, licences, and permissions for content you publish</li>
        <li>Compliance with applicable advertising, disclosure, and endorsement regulations</li>
      </ul>
      <p>We reserve the right to suspend or terminate access if we reasonably believe you are in violation of these Terms or any connected platform's policies.</p>

      <h2 style={{ marginTop: '2rem' }}>3. Ownership and Intellectual Property</h2>
      <p><strong>Your Content:</strong> You retain full ownership of all content you create and publish through the Services. By using the Services, you grant us a limited, non-exclusive licence to process and transmit your content solely for the purpose of providing the Services.</p>
      <p><strong>Our Services:</strong> All software, code, design, trademarks, and intellectual property comprising the Services are owned by S.A.E&trade; / Sylvana Ellis. Nothing in these Terms transfers any ownership rights to you.</p>
      <p><strong>Third-Party Content:</strong> Content generated by or retrieved from third-party platforms remains subject to those platforms' terms and intellectual property rights.</p>

      <h2 style={{ marginTop: '2rem' }}>4. AI-Generated Content Disclaimer</h2>
      <p>The Services may include features that generate content using artificial intelligence, including text, images, and video. You acknowledge and agree that:</p>
      <ul>
        <li>AI-generated content is produced automatically and may not always be accurate, appropriate, or suitable for your purposes</li>
        <li>You are solely responsible for reviewing, approving, and taking responsibility for any AI-generated content before publication</li>
        <li>We make no warranties regarding the accuracy, originality, or fitness for purpose of AI-generated content</li>
        <li>Intellectual property ownership of AI-generated content may be subject to evolving legal interpretation; you use such content at your own risk</li>
        <li>You must not publish AI-generated content that violates any applicable law or third-party rights</li>
      </ul>

      <h2 style={{ marginTop: '2rem' }}>5. Connected Platform Accounts</h2>
      <p>When you connect a third-party social media account (including Facebook, Instagram, LinkedIn, TikTok, YouTube, Google Business Profile, or others), you authorise us to act on your behalf to publish content as directed by you. You confirm that:</p>
      <ul>
        <li>You have the authority to connect and authorise the account</li>
        <li>You will comply with the terms of service of each connected platform</li>
        <li>You understand that platform policies may change and we cannot guarantee continued compatibility</li>
      </ul>
      <p>You may disconnect any connected account at any time through the Services or directly through the respective platform's account settings.</p>

      <h2 style={{ marginTop: '2rem' }}>6. Limitation of Liability</h2>
      <p>To the maximum extent permitted by applicable law, S.A.E&trade; / Sylvana Ellis shall not be liable for:</p>
      <ul>
        <li>Any indirect, incidental, special, consequential, or punitive damages</li>
        <li>Loss of profits, revenue, data, or business opportunities arising from your use of the Services</li>
        <li>Any failure or delay in publishing scheduled content due to platform outages, API changes, or connectivity issues</li>
        <li>Any actions taken by connected social media platforms, including content removal or account suspension</li>
        <li>Inaccuracies or errors in AI-generated content</li>
      </ul>
      <p>The Services are provided "as is" and "as available" without warranties of any kind, express or implied, including but not limited to fitness for a particular purpose or non-infringement.</p>

      <h2 style={{ marginTop: '2rem' }}>7. Account Termination</h2>
      <p>We reserve the right to suspend or terminate your access to the Services at any time, with or without notice, if we determine that:</p>
      <ul>
        <li>You have violated these Terms or any applicable law</li>
        <li>Your use poses a risk to the Services, other users, or third parties</li>
        <li>Continued access is no longer technically or commercially viable</li>
      </ul>
      <p>You may discontinue use of the Services at any time. Upon termination, your right to access the Services ceases immediately. You may request deletion of your stored data by contacting privacy@sae963.com.</p>

      <h2 style={{ marginTop: '2rem' }}>8. Changes to These Terms</h2>
      <p>We may update these Terms from time to time. Continued use of the Services after changes are posted constitutes your acceptance of the revised Terms. We will update the "Last updated" date at the top of this page when changes are made.</p>

      <h2 style={{ marginTop: '2rem' }}>9. Governing Law</h2>
      <p>These Terms are governed by the laws of the Republic of South Africa. Any disputes arising from these Terms or your use of the Services shall be subject to the jurisdiction of the South African courts.</p>

      <h2 style={{ marginTop: '2rem' }}>10. Contact</h2>
      <p>For questions about these Terms:</p>
      <ul style={{ listStyle: 'none', padding: 0 }}>
        <li>Email: privacy@sae963.com</li>
        <li>WhatsApp: +27 84 833 1128</li>
        <li>Website: www.sae963.com</li>
      </ul>

      <p style={{ marginTop: '2rem', color: 'var(--text-muted)', fontSize: '0.875rem' }}>© 2026 S.A.E&trade; | sae963.com — All rights reserved.</p>
    </div>
  );
}